# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\markveligod\Desktop\DSD\widgets\getBlock.ui',
# licensing of 'C:\Users\markveligod\Desktop\DSD\widgets\getBlock.ui' applies.
#
# Created: Sun Apr 28 17:48:45 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_reg(object):
    def setupUi(self, reg):
        reg.setObjectName("reg")
        reg.resize(335, 389)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(reg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(reg)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(78, -1, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.login = QtWidgets.QLineEdit(self.groupBox_2)
        self.login.setObjectName("login")
        self.horizontalLayout_7.addWidget(self.login)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(71, -1, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.password = QtWidgets.QLineEdit(self.groupBox_2)
        self.password.setObjectName("password")
        self.horizontalLayout_8.addWidget(self.password)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(12, -1, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.rep_password = QtWidgets.QLineEdit(self.groupBox_2)
        self.rep_password.setObjectName("rep_password")
        self.horizontalLayout_11.addWidget(self.rep_password)
        self.horizontalLayout_11.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(0, -1, 6, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.foto = QtWidgets.QLineEdit(self.groupBox_2)
        self.foto.setObjectName("foto")
        self.horizontalLayout_13.addWidget(self.foto)
        self.foto_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.foto_btn.setMaximumSize(QtCore.QSize(30, 20))
        self.foto_btn.setObjectName("foto_btn")
        self.horizontalLayout_13.addWidget(self.foto_btn)
        self.horizontalLayout_13.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(reg)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(78, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.name = QtWidgets.QLineEdit(self.groupBox)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(54, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.surname = QtWidgets.QLineEdit(self.groupBox)
        self.surname.setObjectName("surname")
        self.horizontalLayout_2.addWidget(self.surname)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(54, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.patronymic = QtWidgets.QLineEdit(self.groupBox)
        self.patronymic.setObjectName("patronymic")
        self.horizontalLayout_4.addWidget(self.patronymic)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.registration = QtWidgets.QLineEdit(self.groupBox)
        self.registration.setObjectName("registration")
        self.horizontalLayout_3.addWidget(self.registration)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(4, -1, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.residence = QtWidgets.QLineEdit(self.groupBox)
        self.residence.setObjectName("residence")
        self.horizontalLayout_5.addWidget(self.residence)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(19, -1, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(23, 59, 59)))
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1920, 9, 14), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_6.addWidget(self.dateEdit)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.send_btn = QtWidgets.QPushButton(reg)
        self.send_btn.setObjectName("send_btn")
        self.horizontalLayout_12.addWidget(self.send_btn)
        self.close_btn = QtWidgets.QPushButton(reg)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_12.addWidget(self.close_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)

        self.retranslateUi(reg)
        QtCore.QMetaObject.connectSlotsByName(reg)

    def retranslateUi(self, reg):
        reg.setWindowTitle(QtWidgets.QApplication.translate("reg", "Blockchain DSD", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("reg", "Основные данные", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("reg", "Логин:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("reg", "Пароль:", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("reg", "Повторный пароль:", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("reg", "Фотография:", None, -1))
        self.foto_btn.setText(QtWidgets.QApplication.translate("reg", "...", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("reg", "Паспортные данные", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("reg", "Имя:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("reg", "Фамилия:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("reg", "Отчество", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("reg", "Место регистрации:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("reg", "Место жительства:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("reg", "Дата рождения:", None, -1))
        self.send_btn.setText(QtWidgets.QApplication.translate("reg", "Отправить", None, -1))
        self.close_btn.setText(QtWidgets.QApplication.translate("reg", "Закрыть", None, -1))

